# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HeritageInventory
                                 A QGIS plugin
 This is a digital inventory worksheet that collects information about heritage resources.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-27
        copyright            : (C) 2023 by Anna Sanasaryan
        email                : ansa16a@upv.edu.es, annasanasaryan@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load HeritageInventory class from file HeritageInventory.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .her_inv import HeritageInventory
    from . import her_inv_main
    return HeritageInventory(iface)
